#!/bin/bash

# ============================================
# Generate Per-Service Encryption Keys
# ============================================
# This script generates unique encryption keys
# for each microservice in the EduMind platform
#
# Usage: ./generate-all-service-keys.sh
# ============================================

echo "🔐 Generating Per-Service Encryption Keys for EduMind..."
echo ""

# Generate unique 32-byte (256-bit) keys for each service
AUTH_KEY=$(openssl rand -base64 32)
LMS_CORE_KEY=$(openssl rand -base64 32)

echo "✅ Keys Generated Successfully!"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "📋 COPY TO YOUR .env FILE"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "# ============================================"
echo "# ENCRYPTION KEYS - PER SERVICE"
echo "# Generated: $(date)"
echo "# ============================================"
echo ""
echo "# Auth Service - Encrypts: 2FA secrets, OAuth tokens"
echo "ENCRYPTION_KEY=$AUTH_KEY"
echo ""
echo "# LMS Core Service - Encrypts: Sensitive student data, payment info"
echo "LMS_CORE_ENCRYPTION_KEY=$LMS_CORE_KEY"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "⚠️  CRITICAL SECURITY WARNINGS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1. 🔒 Keep these keys SECRET - Never share or commit to Git"
echo "2. 🚫 Add .env to .gitignore immediately"
echo "3. 🔑 Use DIFFERENT keys for dev/staging/production"
echo "4. 🏢 Store production keys in AWS Secrets Manager or Vault"
echo "5. 🔄 Rotate keys quarterly (every 3 months)"
echo "6. 📝 Document key rotation procedures"
echo "7. 👥 Limit access - Only DevOps team should see production keys"
echo "8. 📊 Enable audit logging for key access"
echo "9. ⚠️  NEVER reuse the same key across services"
echo "10. 🔐 Each service's encrypted data becomes unreadable if key changes"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "📝 NEXT STEPS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1. Create .env file if not exists:"
echo "   $ touch .env"
echo ""
echo "2. Copy the keys above into .env"
echo ""
echo "3. Verify .env is in .gitignore:"
echo "   $ grep -q '.env' .gitignore || echo '.env' >> .gitignore"
echo ""
echo "4. Test locally:"
echo "   # Start databases"
echo "   $ docker-compose up -d postgres-auth postgres-lms-core"
echo "   "
echo "   # Run Auth Service"
echo "   $ export ENCRYPTION_KEY=$AUTH_KEY"
echo "   $ mvn spring-boot:run -pl auth-service"
echo "   "
echo "   # Run LMS Core Service"
echo "   $ export LMS_CORE_ENCRYPTION_KEY=$LMS_CORE_KEY"
echo "   $ mvn spring-boot:run -pl lms-core-service"
echo ""
echo "5. For production, store in AWS Secrets Manager:"
echo "   # Auth Service Key"
echo "   $ aws secretsmanager create-secret \\"
echo "       --name edumind/auth-service/encryption-key \\"
echo "       --secret-string \"$AUTH_KEY\""
echo ""
echo "   # LMS Core Service Key"
echo "   $ aws secretsmanager create-secret \\"
echo "       --name edumind/lms-core-service/encryption-key \\"
echo "       --secret-string \"$LMS_CORE_KEY\""
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "🔍 KEY USAGE BY SERVICE"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Auth Service (ENCRYPTION_KEY):"
echo "  • Two-Factor Authentication (2FA) secrets"
echo "  • OAuth2 tokens (Google, Facebook)"
echo "  • Refresh tokens"
echo "  • Temporary authentication codes"
echo ""
echo "LMS Core Service (LMS_CORE_ENCRYPTION_KEY):"
echo "  • Student personal information"
echo "  • Payment and billing data"
echo "  • Grade and assessment records"
echo "  • Confidential course materials"
echo "  • Private messaging content"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Done! Keys are ready to use."
echo "💡 Tip: Save this output securely before closing the terminal"
echo ""