package com.edumind.lms.config.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.ExpiredJwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.MalformedJwtException;
import io.jsonwebtoken.UnsupportedJwtException;
import io.jsonwebtoken.security.Keys;
import jakarta.annotation.PostConstruct;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;

/**
 * Lightweight JWT helper for resource services.
 * Validates tokens that are generated by auth-service and exposes user claims.
 */
@Slf4j
@Component
public class JwtTokenProvider {

    @Value("${jwt.secret}")
    private String jwtSecret;

    private SecretKey signingKey;

    @PostConstruct
    void init() {
        if (!StringUtils.hasText(jwtSecret) || jwtSecret.length() < 32) {
            throw new IllegalStateException("JWT secret must be configured and at least 32 characters long");
        }
        this.signingKey = Keys.hmacShaKeyFor(jwtSecret.getBytes(StandardCharsets.UTF_8));
    }

    public boolean validateToken(String token) {
        try {
            parseClaims(token);
            return true;
        } catch (ExpiredJwtException ex) {
            log.warn("Expired JWT token");
        } catch (MalformedJwtException ex) {
            log.warn("Invalid JWT token");
        } catch (UnsupportedJwtException ex) {
            log.warn("Unsupported JWT token");
        } catch (IllegalArgumentException ex) {
            log.warn("JWT claims string is empty");
        }
        return false;
    }

    public Claims parseClaims(String token) {
        return Jwts.parser()
                .verifyWith(signingKey)
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }

    public Collection<? extends GrantedAuthority> extractAuthorities(Claims claims) {
        String rawRoles = claims.get("roles", String.class);
        if (!StringUtils.hasText(rawRoles)) {
            return Collections.emptyList();
        }

        List<String> roleTokens = splitRoles(rawRoles);

        return roleTokens.stream()
                .map(String::trim)
                .filter(StringUtils::hasText)
                .map(role -> role.startsWith("ROLE_")
                        ? role
                        : "ROLE_" + role.replace("ROLE_", "").toUpperCase(Locale.ROOT))
                .map(SimpleGrantedAuthority::new)
                .collect(Collectors.toList());
    }

    public Long extractUserId(Claims claims) {
        Object userId = claims.get("userId");
        if (userId instanceof Number number) {
            return number.longValue();
        }
        if (userId instanceof String str && StringUtils.hasText(str)) {
            try {
                return Long.parseLong(str);
            } catch (NumberFormatException ex) {
                log.warn("Unable to parse userId from token: {}", str);
            }
        }
        return null;
    }

    private List<String> splitRoles(String rawRoles) {
        if (rawRoles.contains(",")) {
            return Arrays.stream(rawRoles.split("\\s*,\\s*")).toList();
        }
        if (rawRoles.contains(" ")) {
            return Arrays.stream(rawRoles.split("\\s+")).toList();
        }
        if (rawRoles.startsWith("[") && rawRoles.endsWith("]")) {
            String trimmed = rawRoles.substring(1, rawRoles.length() - 1);
            return splitRoles(trimmed);
        }
        // Handles concatenated ROLE_*ROLE_* strings
        return Arrays.stream(rawRoles.split("(?=ROLE_)")).toList();
    }
}

